/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectdead;


import com.toedter.calendar.JCalendar;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import java.awt.print.*;
import java.text.*;
import javax.swing.*;
/**
 *
 * @author ADMIN
 */
public class ProjectDead extends javax.swing.JFrame {
    Connection conn;
    /**
     * Creates new form ProjectDead
     */
    
       public void getItemList()
   {
       
       conn = DatabaseConnection.getConnection();
       
       String query = "SELECT * FROM  `solditemtb` ";
       Statement st;
       ResultSet rs;
       
       try {
           st = conn.createStatement();
           rs = st.executeQuery(query);
           while(rs.next())
           {
               int tran = Integer.parseInt((String)rs.getString("transactionid"));
               String code = rs.getString("itemcode");
               int price = rs.getInt("unitprice");
               int quantity = rs.getInt("quantity");
               String date = rs.getString("date");
               
               
               Object[] columns = {"Date","Transaction Id","Itemcode","Unit Price","Quantity"};
               DefaultTableModel model = (DefaultTableModel)solditemtb.getModel();
               
               Object []row = new Object[5];
               
               row[0]= date;
               row[1]= tran;
               row[2]= code;
               row[3]= price;
               row[4]= quantity;
               model.addRow(row);    
           }
       } catch (Exception e) {
           e.printStackTrace();
       }
   }
       
              public void getTranList()
   {
       
       conn = DatabaseConnection.getConnection();
       
       String query = "SELECT * FROM  `transactionsummary` ";
       Statement st;
       ResultSet rs;
       
       try {
           st = conn.createStatement();
           rs = st.executeQuery(query);
           while(rs.next())
           {
               int tran = Integer.parseInt((String)rs.getString("transactionid"));
               String date = rs.getString("date");
               String cname = rs.getString("customername");
               int mobile = rs.getInt("mobile");
               int stotal = rs.getInt("subtotal");
               int dis = rs.getInt("discount");
               int t = rs.getInt("total");
               
               
               
               Object[] columns = {"Date","Transaction Id","Customername","Mobile","Subtotal","Discount", "Total"};
               DefaultTableModel model = (DefaultTableModel)transactiontb.getModel();
               Object []row = new Object[7];
               
               row[0]= date;
               row[1]= tran;
               row[2]= cname;
               row[3]= mobile;
               row[4]= stotal;
               row[5]= dis;
               row[6]= t;
               model.addRow(row);    
           }
       } catch (Exception e) {
           e.printStackTrace();
       }
   }
   
   

    public ProjectDead() {
        initComponents();
        setVisible(true);
        getItemList();
        getTranList();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        print = new javax.swing.JButton();
        transaction = new javax.swing.JButton();
        stock = new javax.swing.JButton();
        additem = new javax.swing.JButton();
        addcustomer = new javax.swing.JButton();
        transactiontab = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        solditemtb = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        transactiontb = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        from = new com.toedter.calendar.JDateChooser();
        to = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home Page");
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Homepage");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addGap(298, 298, 298))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        print.setFont(new java.awt.Font("Vivaldi", 1, 36)); // NOI18N
        print.setForeground(new java.awt.Color(0, 51, 102));
        print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/print-icon.png"))); // NOI18N
        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        transaction.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        transaction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dollar-folder-icon.png"))); // NOI18N
        transaction.setText("Transaction");
        transaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionActionPerformed(evt);
            }
        });

        stock.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        stock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Eye-icon.png"))); // NOI18N
        stock.setText("View Stock");
        stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockActionPerformed(evt);
            }
        });

        additem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        additem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cart-add-icon.png"))); // NOI18N
        additem.setText("Add Item");
        additem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additemActionPerformed(evt);
            }
        });

        addcustomer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addcustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Actions-list-add-icon.png"))); // NOI18N
        addcustomer.setText("Add Customer");
        addcustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addcustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(additem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(stock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(transaction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(print, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(transaction, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(stock, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(additem, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(addcustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        solditemtb.setAutoCreateRowSorter(true);
        solditemtb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        solditemtb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Transaction Id", "Itemcode", "Unit Price", "Quantity"
            }
        ));
        solditemtb.setRowHeight(25);
        solditemtb.setRowMargin(2);
        jScrollPane1.setViewportView(solditemtb);

        transactiontab.addTab("Sold Item", jScrollPane1);

        transactiontb.setAutoCreateRowSorter(true);
        transactiontb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        transactiontb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Transaction Id", "Customer Name", "Mobile", "Subtotal", "Discount", "Total"
            }
        ));
        transactiontb.setRowHeight(30);
        transactiontb.setShowVerticalLines(false);
        jScrollPane2.setViewportView(transactiontb);

        transactiontab.addTab("Transaction History", jScrollPane2);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("To :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("From :");

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Search-icon.png"))); // NOI18N
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        from.setDateFormatString("yyyy-M-dd");

        to.setDateFormatString("yyyy-M-dd");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(from, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(to, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(search, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(from, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Apps-session-logout-icon.png"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(transactiontab)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(transactiontab))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        int s = select();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        

        String f = sdf.format(from.getDate());
        String t = sdf.format(to.getDate());


       conn = DatabaseConnection.getConnection();
      if(s==0)
      {   
       String query = "SELECT * FROM  `solditemtb` where date BETWEEN '"+f+"' and '"+t+"'";
       
       
       Statement st;
       ResultSet rs;
       
       try {
           st = conn.createStatement();
           rs = st.executeQuery(query);
           DefaultTableModel model = new DefaultTableModel();
           model.setColumnIdentifiers(new Object[]{"Date","Transaction Id","Itemcode","Unit Price","Quantity"});
           Object []row = new Object[5];
           while(rs.next())
           {
               int tran = Integer.parseInt((String)rs.getString("transactionid"));
               String code = rs.getString("itemcode");
               int price = rs.getInt("unitprice");
               int quantity = rs.getInt("quantity");
               String date = rs.getString("date");
     
               row[0]= date;
               row[1]= tran;
               row[2]= code;
               row[3]= price;
               row[4]= quantity;
               model.addRow(row);    
           }
           solditemtb.setModel(model);
           
       } catch (Exception e) {
           e.printStackTrace();
       }
    }
      else{
      String query = "SELECT * FROM  `transactionsummary` where date BETWEEN '"+f+"' and '"+t+"'";
       
       
       Statement st;
       ResultSet rs;
       
       try {
           st = conn.createStatement();
           rs = st.executeQuery(query);
           DefaultTableModel model = new DefaultTableModel();
           model.setColumnIdentifiers(new Object[]{"Date","Transaction Id","Customername","Mobile","Subtotal","Discount", "Total"});
           Object []row = new Object[7];
           while(rs.next())
           {
               int tran = Integer.parseInt((String)rs.getString("transactionid"));
               String date = rs.getString("date");
               String cname = rs.getString("customername");
               int mobile = rs.getInt("mobile");
               int stotal = rs.getInt("subtotal");
               int dis = rs.getInt("discount");
               int to = rs.getInt("total");

               row[0]= date;
               row[1]= tran;
               row[2]= cname;
               row[3]= mobile;
               row[4]= stotal;
               row[5]= dis;
               row[6]= to;    
               model.addRow(row);
           }
           transactiontb.setModel(model);
           
       } catch (Exception e) {
           e.printStackTrace();
       }
      }
        
    }//GEN-LAST:event_searchActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Login log = new Login();
        log.login1();
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void transactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionActionPerformed
        // TODO add your handling code here:
        Transaction tran = new Transaction();
        tran.Transaction1();
        setVisible(false);
    }//GEN-LAST:event_transactionActionPerformed

    private void stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockActionPerformed
        // TODO add your handling code here:
        View v = new View();
        setVisible(false);
    }//GEN-LAST:event_stockActionPerformed

    private void additemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additemActionPerformed
        // TODO add your handling code here:
        AddItem add = new AddItem();
        setVisible(false);
    }//GEN-LAST:event_additemActionPerformed

    private void addcustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcustomerActionPerformed
        // TODO add your handling code here:
        Addcustomer cus = new Addcustomer();
        setVisible(false);
    }//GEN-LAST:event_addcustomerActionPerformed
    
    public int select(){
        int i = transactiontab.getSelectedIndex();
        return i;
    }
    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        
        
        
        MessageFormat Header = new MessageFormat("Report Print");
        MessageFormat Footer = new MessageFormat("Page{0,number,integer}");
        
        try{
            int s = select();//selected tab variable
            if(s==0)
            {
            solditemtb.print(JTable.PrintMode.FIT_WIDTH,Header,Footer);
            }
            else{
            transactiontb.print(JTable.PrintMode.FIT_WIDTH,Header,Footer);
            }
            
            
        
        }catch(java.awt.print.PrinterException e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_printActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addcustomer;
    private javax.swing.JButton additem;
    private com.toedter.calendar.JDateChooser from;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton print;
    private javax.swing.JButton search;
    private javax.swing.JTable solditemtb;
    private javax.swing.JButton stock;
    private com.toedter.calendar.JDateChooser to;
    private javax.swing.JButton transaction;
    private javax.swing.JTabbedPane transactiontab;
    private javax.swing.JTable transactiontb;
    // End of variables declaration//GEN-END:variables
}
